name: commit

on:
  push:
   branches: [main]

  pull_request:
   branches: [main]

jobs:
  buildDEB:
    runs-on: ubuntu-latest
    container: ubuntu:20.04

    steps:
    - uses: actions/checkout@v3
    - name: build packets
      run: docker-compose -f docker-compose.yaml up -d

    - name: upload deb artifact
      run: cd readypackets

    - uses: actions/upload-artifact@main
      with:
        name: deb packet
        path: ./*.deb

    - uses: actions/upload-artifact@main
      with:
        name: rpm packet
        path: ./*.rpm


