name: commit

on:
  push:
   branches: [main]

  pull_request:
   branches: [main]

jobs:
  buildDEB:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build packets
      run: docker-compose -f docker-compose.yaml up -d

    - name: Sleep until packets is ready
      run: sleep 30s

    - name: upload deb artifact
      run: |
         cd readypackets
         ls

    - uses: actions/upload-artifact@main
      with:
        name: deb packet
        path: readypackets/*.deb

    - uses: actions/upload-artifact@main
      with:
        name: rpm packet
        path: readypackets/*.rpm


